### ISSUE TITLE
stock_daily_learning.py 오류 수정 부탁드립니다.

### ISSUE THREAD

**Issue by ggomong** [ggomong/finance_learning#1]
실행하면 아래처럼 오류가 발생되는데 이유가 뭘까요?

Traceback (most recent call last):
  File "stock_daily_learning.py", line 125, in <module>
    py_x, state_size = model(X, W, B, lstm_size)
  File "stock_daily_learning.py", line 41, in model
    XT = tf.transpose(X, [1, 0, 2])  # permute time_step_size and batch_size
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/array_ops.py", line 1100, in transpose
    ret = gen_array_ops.transpose(a, perm, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2903, in transpose
    result = _op_def_lib.apply_op("Transpose", x=x, perm=perm, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2382, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1783, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/array_ops.py", line 1762, in _TransposeShape
    return common_shapes.call_cpp_shape_fn(op, input_tensors_needed=[1])
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Dimension must be 2 but is 3

**Comment by ggomong** [comment]
오류 수정했습니다. ^^
